import sqlite3

with sqlite3.connect("bookinfo.db") as db:cursor=db.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS Authors(name text PRIMARY KEY NOT NULL,PlaceOfBirth text NOT NULL);""")

cursor.execute("""CREATE TABLE IF NOT EXISTS Books(id integer PRIMARY KEY,title text NOT NULL,Author text NOT NULL,DatePublished integer NOT NULL);""")

cursor.execute("""INSERT INTO Authors(name, PlaceOfBirth)
VALUES("Agatha Christie", "Torquay")""")
cursor.execute("""INSERT INTO Authors(name, PlaceOfBirth)
VALUES("Cecelia Ahern", "Dublin")""")
cursor.execute("""INSERT INTO Authors(name, PlaceOfBirth)
VALUES("J. K. Rowling", "Bristol")""")
cursor.execute("""INSERT INTO Authors(name, PlaceOfBirth)
VALUES("Oscar Wilde", "Dublin")""")

cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("1", "De Profundis", "Oscar Wilde", 1905)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("2", "Harry Potter and the chamber of secrets", "J. K. Rowling", 1998)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("3", "Harry Potter and the prisoner of Azkaban", "J. K. Rowling", 1999)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("4", "Lyrebird", "Cecelia Ahern", 2017)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("5", "Murder on the Orient Express", "Agatha Christie", 1934)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("6", "Perfect", "Cecelia Ahern", 2017)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("7", "The marble collector", "Cecelia Ahern", 2016)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("8", "The murder on the links", "Agatha Christie", 1923)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("9", "The picture of Dorian Gray", "Oscar Wilde", 1890)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("10", "The secret adversary", "Agatha Christie", 1921)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("11", "The seven dials mystery", "Agatha Christie", 1929)""")
cursor.execute("""INSERT INTO Books(id, title, Author, DatePublished)
VALUES("12", "The year I met you", "Cecelia Ahern", 2014)""")
db.commit()
db.close()
